/**
 * offlineQueue.ts
 *
 * Typed IndexedDB wrapper for the offline mutation queue.
 * Mirrors the schema used in sw.js — both sides must agree on
 * DB name, store name, and the shape of QueuedMutation.
 *
 * Usage (in components / hooks):
 *
 *   import { offlineQueue } from '@/lib/offlineQueue';
 *
 *   const count = await offlineQueue.count();
 *   const items = await offlineQueue.getAll();
 *   await offlineQueue.remove(id);
 *   await offlineQueue.clear();
 */

export interface QueuedMutation {
  /** UUID generated by the service worker at queue time. */
  id: string;
  /** Unix timestamp (ms) when the mutation was queued. */
  timestamp: number;
  method: 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  url: string;
  headers: Record<string, string>;
  body: string;
}

const DB_NAME    = 'gnosis-offline-queue';
const STORE_NAME = 'mutations';
const DB_VERSION = 1;

function openDB(): Promise<IDBDatabase> {
  return new Promise((resolve, reject) => {
    const req = indexedDB.open(DB_NAME, DB_VERSION);
    req.onupgradeneeded = () => {
      if (!req.result.objectStoreNames.contains(STORE_NAME)) {
        req.result.createObjectStore(STORE_NAME, { keyPath: 'id' });
      }
    };
    req.onsuccess = () => resolve(req.result);
    req.onerror   = () => reject(req.error);
  });
}

async function getAll(): Promise<QueuedMutation[]> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly');
    const req = tx.objectStore(STORE_NAME).getAll();
    req.onsuccess = () =>
      resolve(
        (req.result as QueuedMutation[]).sort(
          (a, b) => a.timestamp - b.timestamp
        )
      );
    req.onerror = () => reject(req.error);
  });
}

async function count(): Promise<number> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readonly');
    const req = tx.objectStore(STORE_NAME).count();
    req.onsuccess = () => resolve(req.result as number);
    req.onerror   = () => reject(req.error);
  });
}

async function remove(id: string): Promise<void> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readwrite');
    const req = tx.objectStore(STORE_NAME).delete(id);
    req.onsuccess = () => resolve();
    req.onerror   = () => reject(req.error);
  });
}

async function clear(): Promise<void> {
  const db = await openDB();
  return new Promise((resolve, reject) => {
    const tx  = db.transaction(STORE_NAME, 'readwrite');
    const req = tx.objectStore(STORE_NAME).clear();
    req.onsuccess = () => resolve();
    req.onerror   = () => reject(req.error);
  });
}

/** Trigger a manual sync via the service worker (fallback for browsers
 *  without Background Sync API support). */
export async function triggerManualSync(): Promise<void> {
  // Guard against environments where serviceWorker is absent OR explicitly
  // set to undefined (e.g. in tests that stub the property away).
  if (!navigator.serviceWorker) return;
  const reg = await navigator.serviceWorker.ready;
  if ('sync' in reg) {
    // Background Sync supported — let the browser schedule it
    await (reg as unknown as { sync: { register(tag: string): Promise<void> } })
      .sync.register('gnosis-sync-mutations');
  } else {
    // Fallback: post a message to the active SW to drain immediately
    reg.active?.postMessage({ type: 'SYNC_NOW' });
  }
}

export const offlineQueue = { getAll, count, remove, clear };
